name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -fsSL https://deno.land/x/install/install.sh | sh
      - run: /home/runner/.deno/bin/deno test --allow-net
